added safety net for improved compatibility with Nimble mod
OceanUwU/sts-bogwarden-char pull request #4
Opened 2024-02-13 08:48 UTC by henningkoehlernz

Also triggers traps when AbstractPlayer.updateCardsOnDamage is called. This only has an effect if the normal triggers are bypassed by other mods.

2024-02-13 16:34 UTC, OceanUwU requested changes

2024-02-13 16:34 UTC, OceanUwU commented on src/main/java/bogwarden/patches/TrapPatches.java
> +    @SpirePatch(clz=AbstractPlayer.class, method="updateCardsOnDamage")
looks like this patch will always occur before the usual TriggerOnDamage one, making the trap target always random.
i'd suggest removing the original triggerondamage insert patch, and in its existing prefix patch storing the damageinfo for use later in this patch for its target.

2024-02-13 17:02 UTC, OceanUwU requested changes
this fix breaks with nimble mod depending on the load order - if nimble mod loads second it blocks this prefix patch on damage with its spirereturn, making it so traps will only be able to trigger once until the game restarts.

not sure what the best way to go about fixing this is, but an idea that immediately comes to mind is adding nimble mod as one of the [optional_dependencies](https://github.com/kiooeht/ModTheSpire/wiki/ModInfo) of bogwarden

2024-02-14 01:32 UTC, henningkoehlernz commented
Good catch on my patch actually triggering before the original insert - I had been using IntelliJ decompiler (rather than JD-GUI) for line counting and got the position of rloc=101 wrong. Sorry about that.
Regarding the conflict with Nimble due to load order, I just pushed an update on my end that should resolve this (Nimble damage patch now inserts right before decrementBlock).

2024-02-14 11:03 UTC, OceanUwU approved these changes

2024-02-14 11:03 UTC, merged